apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-org/my-app-repo.git'
    targetRevision: HEAD
    path: 'manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
